# Generated by Django 2.0.5 on 2019-04-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190414_1202'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttriage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='patienttriage',
            name='organization',
        ),
        migrations.AddField(
            model_name='patient',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.Organization'),
            preserve_default=False,
        ),
    ]
