# Generated by Django 2.0.5 on 2019-04-20 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190414_1202'),
        ('patients', '0002_auto_20190415_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='event',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organization',
        ),
        migrations.AddField(
            model_name='patienttriage',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienttriage',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Organization'),
            preserve_default=False,
        ),
    ]
