# Generated by Django 2.0.5 on 2019-04-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20190420_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='time_of_death',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
